blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.BlogListView.as_view(), name='blog'),
    path('<int:pk>/', views.BlogDetailView.as_view(), name='post_detail'),
]

poll_project/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts.views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('polls/', include('polls.urls')),
    path('blog/', include('blog.urls')),
    path('accounts/', include('accounts.urls')),
]

blog/models.py
from django.db import models


class Post(models.Model):
    """
    Represents a blog post.

    :ivar title: The title of the blog post.
    :vartype title: str
    :ivar body: The main content/body of the blog post.
    :vartype body: str
    :ivar signature: A short signature or author line for the post.
    :vartype signature: str
    :ivar date: The date and time the post was created.
    :vartype date: datetime
    """
    title = models.CharField(max_length=200)
    body = models.TextField()
    signature = models.CharField(max_length=140, default="~ By Malaika Nkosi")
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """
        Returns the string representation of the post.

        :return: The title of the blog post.
        :rtype: str
        """
        return self.title

blog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, DetailView
from .models import Post


class BlogListView(LoginRequiredMixin, ListView):
    """
    Displays a list of all blog posts.

    Inherits from Django's ListView and requires the user to be logged in
    via LoginRequiredMixin.

    :ivar model: The model used for the list view (Post).
    :vartype model: Model
    :ivar template_name: The path to the HTML template used to render the list view.
    :vartype template_name: str
    :ivar login_url: The URL to redirect to if the user is not authenticated.
    :vartype login_url: str
    """
    model = Post
    template_name = 'blog.html'
    login_url = 'login'  # Redirects to this URL if not authenticated


class BlogDetailView(LoginRequiredMixin, DetailView):
    """
    Displays the details of a single blog post.

    Inherits from Django's DetailView and requires the user to be logged in
    via LoginRequiredMixin.

    :ivar model: The model used for the detail view (Post).
    :vartype model: Model
    :ivar template_name: The path to the HTML template used to render the detail view.
    :vartype template_name: str
    :ivar login_url: The URL to redirect to if the user is not authenticated.
    :vartype login_url: str
    """
    model = Post
    template_name = 'post.html'
    login_url = 'login'

blog/templates/blog.html
{% include 'header.html' %}
<h2 class="mb-4">Blog Posts</h2>
{% for post in object_list %}
    <div class="card mb-3">
        <div class="card-body">
            <h5 class="card-title">{{ post.title }}</h5>
            <p class="card-text">{{ post.body|truncatewords:30 }}</p>
            <a href="{% url 'blog:post_detail' post.pk %}" class="btn btn-primary">Read More</a>
        </div>
    </div>
{% endfor %}
<h2><a href="{% url 'home' %}" class="btn btn-secondary">Go To Home Page</a></h2>
</div>
</body>
</html>

blog/templates/header.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>My Blog</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <nav class="navbar navbar-dark bg-dark mb-4">
        <div class="container">
            <a class="navbar-brand" href="/blog/">My Blog</a>
        </div>
    </nav>
    <div class="container">

blog/templates/post.html
{% include 'header.html' %}
<h2>{{ object.title }}</h2>
<p class="text-muted">{{ object.date }}</p>
<p>{{ object.body }}</p>
<hr>
<p class="text-end text-primary fw-bold">{{ object.signature }}</p>
<a href="{% url 'blog:blog' %}" class="btn btn-secondary">Back to Blog Page</a>
</div>
</body>
</html>